name: Push beta rebase
description: 'Pushes rebase to origin on success'

runs:
  using: "composite"
  steps:
    - name: Push rebase to origin
      shell: bash
      run: |
        git push --force origin beta
