name: Auto-rebase beta onto main
description: Rebase beta branch onto main branch

runs:
  using: composite
  steps:
    - name: Rebase
      shell: bash
      run: |
        git fetch

        if ! git rebase origin/main; then
          echo "Rebase failed due to conflicts."
          git rebase --abort
          exit 1
        fi
