name: Build beta

on:
  workflow_call:
    inputs:
      rebase:
        description: 'Whether to rebase before building'
        required: false
        type: boolean

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-beta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: beta
      
      - id: rebase-beta
        uses: ./.github/actions/rebase-beta
        if: ${{ inputs.rebase }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci --force
      
      - name: Force install latest chirilang & weaving
        run: |
          LATEST_COMMIT=$(curl -s https://api.github.com/repos/fluff4me/chiri/commits/package | jq -r '.sha')
          npm install github:fluff4me/chiri#$LATEST_COMMIT
          LATEST_COMMIT=$(curl -s https://api.github.com/repos/ChiriVulpes/weaving/commits/package | jq -r '.sha')
          npm install github:ChiriVulpes/weaving#$LATEST_COMMIT

      - name: Build
        env:
          ENVIRONMENT: beta
          API_ORIGIN: https://api.fluff4.me/
          URL_ORIGIN: https://fluff4.me/beta/
          BUILD_NUMBER: ${{ github.run_number }}
          BUILD_SHA: ${{ github.sha }}
        run: npm run build

      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: build-beta
          build_dir: docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/revert-beta
        if: ${{ inputs.rebase && failure() && steps.rebase-beta.outcome == 'success' }}
