name: Build

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci --force
      
      - name: Force install latest chirilang & weaving
        run: |
          LATEST_COMMIT=$(curl -s https://api.github.com/repos/fluff4me/chiri/commits/package | jq -r '.sha')
          npm install github:fluff4me/chiri#$LATEST_COMMIT
          LATEST_COMMIT=$(curl -s https://api.github.com/repos/ChiriVulpes/weaving/commits/package | jq -r '.sha')
          npm install github:ChiriVulpes/weaving#$LATEST_COMMIT

      - name: Calculate Run Number
        env:
          NUM: ${{ github.run_number }}
        run: echo "BUILD_NUMBER=$(($NUM+0))" >> "$GITHUB_ENV"

      - name: Build
        env:
          API_ORIGIN: https://api.fluff4.me/
          URL_ORIGIN: https://fluff4.me/
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          BUILD_SHA: ${{ github.sha }}
        run: npm run build

      - name: Notify Discord on failure
        if: failure()
        run: npm run notify
        env:
          BUILD_WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}
          NOTIFY_TYPE: failure
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          fqdn: fluff4.me
          target_branch: build
          build_dir: docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
