name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Clear .git folders (no submodules here!)
        run: |
          rm -rf .git
      
      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: deploy
          build_dir: "."
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Setup Node.js environment
        if: success()
        uses: actions/setup-node@v4

      - name: Install dependencies
        if: success()
        run: npm ci --force

      - name: Notify Discord
        if: success()
        run: npm run notify
        env:
          BUILD_WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}
          NOTIFY_TYPE: success
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
