name: Push main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [build]
    if: always() && needs.build.result == 'success'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
